[Service]
ExecStart=
ExecStart=/bin/sh -c 'D=/dev/fastrpc-adsp-secure; [ -e "$D" ] || D=/dev/fastrpc-adsp; exec /usr/libexec/hexagonrpc/hexagonrpcd -f "$D" -d adsp -s -R /var/lib/droid-juicer/sensors/'
